### ISSUE TITLE
You should never commit data or binary blobs to a git repo

### ISSUE THREAD

**Issue by sg-s** [cosmojg/liu-control#9]
So no .mat files. Only things that can be viewed with a text editor are permissible

**Comment by cosmojg** [comment]
Normally, I would agree with you on this, but the cache files in question are so small, equivalent in magnitude to plaintext data, that I figured the benefits of making that data public outweighed the possible negative side effects. Also, since I don't plan on making any changes to those files, their presence shouldn't bloat the git history either.

Is there something I'm missing?

**Comment by sg-s** [comment]
> Also, since I don't plan on making any changes to those files

https://github.com/cosmojg/liu-control/issues/8

**Comment by cosmojg** [comment]
Ah. Point taken. I'll get to work.

**Comment by sg-s** [comment]
committing binary files always starts small -- oh, the file is small, or i'm never going to change it, and a few weeks down the line, your git repo is in the GB range

**Comment by sg-s** [comment]
real world example:

https://github.com/marderlab/Otopalik-Pipkin-Marder-2019

is several GB
